name: Create Branch on Label

on:
  pull_request:
    types:
      - labeled

jobs:
  create_branch:
    if: contains(github.event.label.name, 'merge-done')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all branches and history

      - name: Configure Git
        run: |
          git config user.name "android-bot"
          git config user.email "ag7aka@gmail.com"

      - name: Create new branch from PR base branch
        env:
          BRANCH_NAME: "feature/${{ github.event.pull_request.number }}"  # Custom branch name
        run: |
          git checkout -b "$BRANCH_NAME" "${{ github.event.pull_request.base.ref }}"
          git push origin "$BRANCH_NAME"
