name: Create Branch on Label

on:
  pull_request:
    types:
      - labeled  # Triggers when any label is added to a PR

jobs:
  create_branch:
    if: github.event.label.name == 'create-pr'  # Checks for "create-pr" label specifically
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config user.name "Android-bot"
          git config user.email "android_bot@a7.com"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Feature PR"
          body: "This PR includes changes for my feature."
          branch: feature/2  # Use 'branch' instead of 'head'
          base: dev
          token: ${{ secrets.TOKEN }}
